name: Build & Release YTDownloader

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write    

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Publish single EXE
        run: dotnet publish -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true -p:EnableCompressionInSingleFile=true -o publish

      - name: Download yt-dlp.exe
        run: |
          Invoke-WebRequest -Uri https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp.exe -OutFile publish/yt-dlp.exe

      - name: Package into ZIP
        run: |
          Compress-Archive -Path publish/* -DestinationPath YTDownloader-${{ github.ref_name }}.zip

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: YTDownloader
          path: YTDownloader-${{ github.ref_name }}.zip

  release:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: YTDownloader

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: YTDownloader-${{ github.ref_name }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
